### ISSUE TITLE
[Enhancement] Bad GUI

### ISSUE THREAD

**Issue by SpyCoder77** [Aeldit/CTMSelector#2]
Please make it have a better gui and block categories such as stone and wood and logs

**Comment by Aeldit** [comment]
This is planned with the controls, but I'll try to implement a basic version with just files paths before that

**Comment by Aeldit** [comment]
Fixed with [3d87b3c](https://github.com/Aeldit/CTMSelector/commit/3d87b3cbbcc345b9b23ab6dfec0cccea09d163fe)

**Comment by SpyC0der77** [comment]
What about the categories

**Comment by Aeldit** [comment]
That is exactly what was added, I just called it controls but it adds categories
